require('dotenv').config({ path:process.cwd()+ '/.env' })

module.exports ={
 
START_PROJECT:process.env.START_PROJECT,


DB_SERVER_DEV:process.env.DB_SERVER_DEV,
DB_USERNAME_DEV:process.env.DB_USERNAME_DEV,
DB_PASSWORD_DEV:process.env.DB_PASSWORD_DEV,
DB_NAME_DEV:process.env.DB_NAME_DEV,
DB_PORT_DEV:process.env.DB_PORT_DEV,
LOG_DB_SERVER_DEV:process.env.LOG_DB_SERVER_DEV,
LOG_DB_USERNAME_DEV:process.env.LOG_DB_USERNAME_DEV,
LOG_DB_PASSWORD_DEV:process.env.LOG_DB_PASSWORD_DEV,
LOG_DB_NAME_DEV:process.env.LOG_DB_NAME_DEV,
LOG_DB_PORT_DEV:process.env.LOG_DB_PORT_DEV,


HOST:process.env.HOST,
PORT:process.env.PORT,
JWTSECRET:process.env.JWTSECRET,
CUSTOMHERDERKEY:process.env.CUSTOMHERDERKEY,
USERSWAGGER:process.env.USERSWAGGER,
PASSWORDSWAGGER:process.env.PASSWORDSWAGGER,
FIXDATA_MATERIAL_UNIT_PIECE:process.env.FIXDATA_MATERIAL_UNIT_PIECE,
FIXDATA_MATERIAL_UNIT_WEIGHT:process.env.FIXDATA_MATERIAL_UNIT_WEIGHT,
LOGACCESSPATH:process.env.LOGACCESSPATH,
PASSWORDACADEMY:process.env.PASSWORDACADEMY,
}